version: "2"

services:
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  content-forethought:
     image:  content-forethought
     ports:
       - "8080:8080"

  node-exporter:
   image: prom/node-exporter
   ports:
     - "9100:9100"