FROM ubuntu:latest

RUN useradd --no-create-home --shell /bin/false node_exporter

RUN apt-get update && apt-get install -y wget

USER root

WORKDIR /tmp
RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.darwin-amd64.tar.gz && \
    tar xvfz node_exporter-*.*-amd64.tar.gz && \
    chmod a+x node_exporter-*.*-amd64/node_exporter

CMD ./node_exporter-1.5.0.darwin-amd64